<template>

  <div id="app">
    <Header/>
    <AddTodo v-on:add-todo= "addTodo"/>
    <todos v-bind:todos="todos" v-on:del-todo="deleteTodo"/>
    
  </div>
</template>

<script>
//use the import function to import lybraries that you gonna use or other vue instances that you created.
import Header from './components/layout/Header';
import Todos from './components/Todos';
import AddTodo from './components/AddTodo';

//and using the export you can use that information i the other pages of the application
export default {
  name: 'app',
  //dont forget to add to componentes what you want to show on you app froont page 
  components: {
    Header,
    Todos,
    AddTodo,
   
  },
  //need to review here since you learned that data is not reactive , what is this now data () before was data :
  data(){
    return {
      //hard coded elements can be now removed ,this is an array of objects and each has own id..now created by uuid, but it can be generated by the database later.
      todos: [
        {
          id:1,
          title: "Buy Milk",
          completed: false
        },
        {
          id:2,
          title: "Water Plants",
          completed: false
        },
        {
          id:3,
          title: "Clean windows",
          completed: false
        }

        
      ]
    }
      
  },
   methods: {
     //this method to delet elements from the todo list , use a new function called filter (need review on this)
      deleteTodo(id) {
        this.todos = this.todos.filter(todo => todo.id !== id);
      },
      //there is other representations from the tree dots (need review)
      addTodo(newTodo){
        this.todos = [...this.todos, newTodo];
      }
    }
 
}
</script>

<style>
/*Styles here like css , the webkits for working in different browsers, the rest is regular*/
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.btn{
  display:inline-block;
  border: none;
  background: lightcoral;
  color: white;
  padding: 7px 20px;
  cursor: pointer;

}
.btn:hover{
  background: lightblue;
}

</style>
